import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'

export type Language = 'en' | 'es' | 'fr'

type Copy = Record<string, string>

const en: Copy = {
  navArticle: 'Article 12', navWorkflow: 'Your workflow', navOwnership: 'Ownership', navDemo: 'Demo', navDevelopers: 'Developers', navFaq: 'FAQ', requestAccess: 'Request Access',
  heroBadge: 'Regulation (EU) 2024/1689 · Article 12', heroTitleA: 'Every AI decision,', heroTitleB: 'on the record.',
  heroBody: 'Article 12 of the EU AI Act obliges high-risk AI systems to record events automatically, over their entire lifetime. SurStor is the record-keeping layer built for exactly that — tamper-evident log pools, hosted on EU-sovereign infrastructure. And beyond compliance: every output you create with any tool or model becomes your property, portable between them, allocated wherever you choose.',
  heroWorkflow: 'Find your workflow →', heroObligation: 'Read the obligation', heroInForce: 'Art. 12 in force for Annex III systems', heroSince: 'since 02 Aug 2026', heroLive: 'live', heroHash: 'hash-chained · append-only', heroRetention: 'retention ≥ 183 days', heroSeq: 'seq', heroMerkle: 'merkle root', heroRegion: 'Example region',
  journeyEyebrow: 'Find your path / Guided tour', journeyTitle: 'What will you build with SurStor?', journeyBody: 'Choose your workflow. See how it fits, explore an example, and find your next step.', journeyChoose: 'Choose your use case', journeyExplore: 'Explore the workflow', journeyNext: 'Take the next step', journeyShow: 'Show my workflow →', journeyStart: 'How do I get started? →', journeyBack: 'Back', journeyExample: 'Try the example first', journeyReturn: 'Return to your journey', journeyIllustrative: 'The demos use illustrative data.',
  devName: 'Developers', devGoal: 'Keep the context behind your code.', devScenario: 'An AI assistant produces a patch. Save its output and provenance, then compare it with the next revision.', devStep1: 'Store drafts and code outputs in a session.', devStep2: 'Retrieve the agent, model and timestamp behind each artifact.', devStep3: 'Compare text versions with surstor_diff.', devAction: 'Explore a sample session', devNext: 'Connect your local node',
  agentName: 'AI agent builders', agentGoal: 'Follow the work between agents.', agentScenario: 'A research agent hands a brief to a writing agent. Keep their outputs in one traceable session.', agentStep1: 'Capture each agent’s output with an agent ID.', agentStep2: 'Follow the session’s sequence of linked records.', agentStep3: 'Retrieve earlier artifacts for the next step in your workflow.', agentAction: 'Follow the sample handoff',
  researcherName: 'Researchers', researcherGoal: 'Find the work you remember.', researcherScenario: 'You remember a conclusion, but not the wording or the session. Search stored artifacts by meaning and recover the original.', researcherStep1: 'Save your analyses and model outputs.', researcherStep2: 'Search your local node with a natural-language question.', researcherStep3: 'Retrieve the full artifact with its recorded provenance.', researcherAction: 'Explore search examples', researcherNext: 'Set up local search',
  complianceName: 'Compliance teams', complianceGoal: 'Check the integrity of a record.', complianceScenario: 'A reviewer needs to inspect an AI workflow. Export its session and check the records independently.', complianceStep1: 'Capture artifacts with provenance metadata.', complianceStep2: 'Verify content bindings, session links and signatures.', complianceStep3: 'Export a session bundle for offline verification.', complianceAction: 'Try the integrity exercise', complianceNext: 'Discuss your requirements',
  howEyebrow: 'How SurStor works / Four steps', howTitle: 'From AI output to a record you can check.', howBody: 'Connect once, capture the work that matters, and keep a way to find and verify it later.', howConnect: 'Connect', howConnectBody: 'Connect an MCP-compatible client to your local SurStor node. Your workflow decides which outputs to capture.', howConnectDetail: 'Your workflow → your node', howConnectLink: 'Set up your connection', howStore: 'Store', howStoreBody: 'Save an output with its session, agent and model details. SurStor records its provenance and links it into the session history.', howStoreDetail: 'Output → recorded artifact', howStoreLink: 'Explore a sample record', howFind: 'Find', howFindBody: 'Search stored work by meaning, then retrieve the original artifact and its provenance. Search runs on your local node.', howFindDetail: 'Question → original work', howFindLink: 'Try the search examples', howVerify: 'Verify and export', howVerifyBody: 'Check content bindings, session links and signatures. Export a session bundle for independent, offline verification.', howVerifyDetail: 'Session → portable evidence', howVerifyLink: 'Explore integrity checks', howDisclaimer: 'This workflow describes the current local node. The examples below use sample data; verification checks record integrity, not the truth of the original content.',
  demoEyebrow: 'Explore SurStor / Product tour', demoTitle: 'Every output has a story.', demoBody: 'Follow a brief through an AI workflow. Open a record to see what was saved, who produced it, and where it belongs.', demoSearch: 'Try search ↗', demoIntegrity: 'Test integrity ↗', demoConnect: 'Connect your node ↗', demoSession: 'SAMPLE SESSION', demoSessionName: 'Launch planning / 3 records', demoDownload: 'Download sample JSON ↓', demoAgent: 'Agent', demoModel: 'Model', demoCaptured: 'Captured · 18 Sep 2026', demoPrevious: 'Previous record', demoStart: 'Session start', demoDownloaded: 'Sample downloaded. ', demoNotice: 'Illustrative data, kept in your browser. This tour is not connected to a node; the download is not a signed SurStor bundle.',
  recordBrief: 'Client brief', recordBriefType: 'Source note', recordBriefContent: 'The client needs the launch proposal by Friday, 25 September. The approved project budget is $12,000.', recordProposal: 'Launch proposal', recordProposalType: 'AI draft', recordProposalContent: 'Launch in two phases: an internal pilot followed by a public release. Submit the proposal on 25 September and keep delivery within the approved $12,000 budget.', recordReview: 'Review decision', recordReviewType: 'Review note', recordReviewContent: 'The proposal is ready for human review. The public release still needs approval from the client before it can proceed.',
  searchEyebrow: 'Find it again / Semantic search', searchTitleA: 'Remember the meaning.', searchTitleB: 'Find the work.', searchBody: 'Your wording can change. Your work is still there. SurStor’s local node searches stored artifacts by meaning and returns records you can retrieve in full.', searchLocal: 'Embeddings and search run on the node using a bundled model. No external embedding API is needed. The search index can be rebuilt from the stored records.', searchChoose: 'CHOOSE AN EXAMPLE QUESTION', searchMatch: 'Illustrative match', searchWhy1: 'A question about timing leads back to the deadline in the original brief.', searchWhy2: '“Spending limit” connects to the approved budget, even without those exact words.', searchWhy3: 'The review note captures the remaining approval dependency.', searchNotice: 'These are curated examples, not live semantic-search results. Connect a local node to search your own artifacts.', queryDue: 'When is the proposal due?', queryBudget: 'What is the spending limit?', queryApproval: 'Who needs to approve the release?',
  integrityEyebrow: 'Trust the record / Integrity playground', integrityTitleA: 'Change the record.', integrityTitleB: 'See the difference.', integrityBody: 'Edit the sample below, then check it against its original. Even a small change leaves a different record.', integrityLabel: 'Editable sample record', integrityCheck: 'Check record', integrityChanged: 'Try a changed budget', integrityReset: 'Reset', integrityReady: 'Ready. Check the original or make an edit first.', integrityValid: '✓ Unchanged — the sample matches the original.', integrityDetected: '✕ Change detected — the sample no longer matches.', integrityHow: 'How the real node verifies work', integrityBinding: 'Content binding.', integrityContinuity: 'Session continuity.', integritySignature: 'Node signature.', integritySchedule: 'Cost schedule.', integrityFootnote: 'This browser exercise compares text only. Real SurStor verification uses hashes, session links and signatures; it establishes integrity, not whether the original content is true.',
  quickEyebrow: 'Build with SurStor / Developer quickstart', quickTitle: 'Your first verifiable artifact.', quickBody: 'Connect your AI workflow to the current local node. Store an output, retrieve its provenance, and verify the record.', quickSetup: 'Local developer setup.', quickSetupBody: 'Requires a SurStor source checkout. Build the required Covia dependencies from source first, following the checkout’s INTEGRATION_NOTES.md; they are not available from Maven Central. The node trusts local callers and must remain bound to 127.0.0.1.', quickNext: 'Next: use', quickSearch: 'to find artifacts by meaning, or', quickExport: 'to create a portable session bundle for offline verification.', quickStep1: 'Build and start your node', quickStep1Detail: 'From the SurStor source checkout, with Java 21+, Maven and the required Covia artifacts installed locally:', quickStep2: 'Connect an MCP client', quickStep2Detail: 'Use a client that supports streamable HTTP. This is an example MCP configuration; the configuration location depends on your client.', quickStep3: 'Store your first artifact', quickStep3Detail: 'Call surstor_store from the connected client with these arguments. Save the returned id for the next step.', quickStep4: 'Retrieve and verify', quickStep4Detail: 'Call surstor_retrieve with the returned id. Then call surstor_verify with the same id and deep: true to check the session chain as well.', copy: 'Copy', copied: 'Copied', copyFallback: 'Select the code below to copy it manually.',
  ctaEyebrow: '07 / Get ready', ctaTitleA: 'Be auditable.', ctaTitleB: 'Starting today.', ctaBody: 'Article 12 is not a policy you write — it is infrastructure you run, and it is already in force. SurStor onboards EU teams in days, with record-keeping live before your next deployment.', ctaPlaceholder: 'work email', ctaButton: 'Request access', ctaFine: 'eu regions only · no credit card · dpa on day one',
  footerDescription: 'The record-keeping layer for Europe’s AI economy. Decentralized storage, hash-chained logs, EU-sovereign by design.', footerSystems: 'all systems operational — de-fra · nl-ams · ie-dub · se-sto', footerPlatform: 'Platform', footerCompliance: 'Compliance', footerCompany: 'Company', footerLogPools: 'Log pools', footerRetention: 'Retention engine', footerExport: 'Authority export', footerAgents: 'Agent pools', footerPortable: 'Portable memory', footerStatus: 'Status', footerGuide: 'Article 12 guide', footerRetentionGuide: 'Art. 26(6) retention', footerGdpr: 'GDPR interplay', footerPenalties: 'Art. 99 penalties', footerTrust: 'Trust center', footerAbout: 'About', footerResidency: 'EU data residency', footerCareers: 'Careers', footerContact: 'Contact', footerLegal: 'SurStor provides record-keeping infrastructure. Content on this site is informational and does not constitute legal advice.', backJourney: '← Back to your guided journey',
  languageLabel: 'Language', languageEnglish: 'English', languageSpanish: 'Español', languageFrench: 'Français',
}

const es: Copy = {
  ...en,
  navWorkflow: 'Tu flujo de trabajo', navOwnership: 'Propiedad', navDemo: 'Demo', navDevelopers: 'Desarrolladores', requestAccess: 'Solicitar acceso',
  heroBadge: 'Reglamento (UE) 2024/1689 · Artículo 12', heroTitleA: 'Cada decisión de IA,', heroTitleB: 'queda registrada.', heroBody: 'El artículo 12 de la Ley de IA de la UE obliga a los sistemas de IA de alto riesgo a registrar eventos automáticamente durante toda su vida útil. SurStor es la capa de registro creada para ello: grupos de logs con evidencia de manipulación, alojados en infraestructura soberana de la UE. Y más allá del cumplimiento: cada resultado que creas con cualquier herramienta o modelo se convierte en tu propiedad, portable entre ellos y asignable donde decidas.', heroWorkflow: 'Encuentra tu flujo →', heroObligation: 'Lee la obligación', heroInForce: 'El Art. 12 está vigente para sistemas del Anexo III', heroSince: 'desde el 2 ago 2026', heroLive: 'activo', heroHash: 'encadenado por hash · solo anexos', heroRetention: 'retención ≥ 183 días', heroRegion: 'Región de ejemplo',
  journeyEyebrow: 'Encuentra tu ruta / Visita guiada', journeyTitle: '¿Qué construirás con SurStor?', journeyBody: 'Elige tu flujo, descubre cómo encaja, explora un ejemplo y encuentra el siguiente paso.', journeyChoose: 'Elige tu caso de uso', journeyExplore: 'Explora el flujo', journeyNext: 'Da el siguiente paso', journeyShow: 'Mostrar mi flujo →', journeyStart: '¿Cómo empiezo? →', journeyBack: 'Atrás', journeyExample: 'Probar el ejemplo primero', journeyReturn: 'Volver a tu ruta', journeyIllustrative: 'Las demos usan datos ilustrativos.',
  devName: 'Desarrolladores', devGoal: 'Conserva el contexto detrás de tu código.', devScenario: 'Un asistente de IA produce un parche. Guarda su resultado y procedencia, y compáralo con la siguiente versión.', devStep1: 'Guarda borradores y código en una sesión.', devStep2: 'Recupera el agente, modelo y hora de cada artefacto.', devStep3: 'Compara versiones con surstor_diff.', devAction: 'Explorar una sesión de ejemplo', devNext: 'Conectar tu nodo local',
  agentName: 'Creadores de agentes de IA', agentGoal: 'Sigue el trabajo entre agentes.', agentScenario: 'Un agente de investigación entrega un resumen a un agente de redacción. Conserva sus resultados en una sesión trazable.', agentStep1: 'Captura el resultado de cada agente con su ID.', agentStep2: 'Sigue la secuencia de registros enlazados.', agentStep3: 'Recupera artefactos anteriores para el siguiente paso.', agentAction: 'Seguir la transferencia de ejemplo',
  researcherName: 'Investigadores', researcherGoal: 'Encuentra el trabajo que recuerdas.', researcherScenario: 'Recuerdas una conclusión, pero no las palabras ni la sesión. Busca artefactos por significado y recupera el original.', researcherStep1: 'Guarda tus análisis y resultados de modelos.', researcherStep2: 'Busca en tu nodo con una pregunta en lenguaje natural.', researcherStep3: 'Recupera el artefacto completo con su procedencia.', researcherAction: 'Explorar ejemplos de búsqueda', researcherNext: 'Configurar la búsqueda local',
  complianceName: 'Equipos de cumplimiento', complianceGoal: 'Comprueba la integridad de un registro.', complianceScenario: 'Un revisor necesita inspeccionar un flujo de IA. Exporta la sesión y comprueba los registros de forma independiente.', complianceStep1: 'Captura artefactos con metadatos de procedencia.', complianceStep2: 'Verifica referencias de contenido, enlaces de sesión y firmas.', complianceStep3: 'Exporta un paquete de sesión para verificarlo sin conexión.', complianceAction: 'Probar el ejercicio de integridad', complianceNext: 'Hablar sobre tus requisitos',
  howEyebrow: 'Cómo funciona SurStor / Cuatro pasos', howTitle: 'Del resultado de IA a un registro que puedes comprobar.', howBody: 'Conecta una vez, captura el trabajo importante y conserva una forma de encontrarlo y verificarlo después.', howConnect: 'Conecta', howConnectBody: 'Conecta un cliente compatible con MCP a tu nodo local de SurStor. Tu flujo decide qué resultados capturar.', howConnectDetail: 'Tu flujo → tu nodo', howConnectLink: 'Configurar la conexión', howStore: 'Guarda', howStoreBody: 'Guarda un resultado con su sesión, agente y modelo. SurStor registra su procedencia y lo enlaza al historial.', howStoreDetail: 'Resultado → artefacto registrado', howStoreLink: 'Explorar un registro', howFind: 'Encuentra', howFindBody: 'Busca el trabajo por significado y recupera el artefacto original con su procedencia. La búsqueda funciona en tu nodo local.', howFindDetail: 'Pregunta → trabajo original', howFindLink: 'Probar ejemplos de búsqueda', howVerify: 'Verifica y exporta', howVerifyBody: 'Comprueba referencias de contenido, enlaces de sesión y firmas. Exporta un paquete para verificarlo de forma independiente y sin conexión.', howVerifyDetail: 'Sesión → evidencia portable', howVerifyLink: 'Explorar comprobaciones', howDisclaimer: 'Este flujo describe el nodo local actual. Los ejemplos usan datos de muestra; la verificación comprueba la integridad del registro, no la verdad del contenido original.',
  demoEyebrow: 'Explora SurStor / Visita del producto', demoTitle: 'Cada resultado tiene una historia.', demoBody: 'Sigue un resumen a través de un flujo de IA. Abre un registro para ver qué se guardó, quién lo produjo y dónde pertenece.', demoSession: 'SESIÓN DE EJEMPLO', demoSessionName: 'Plan de lanzamiento / 3 registros', demoDownload: 'Descargar JSON de ejemplo ↓', demoAgent: 'Agente', demoModel: 'Modelo', demoCaptured: 'Capturado · 18 sep 2026', demoPrevious: 'Registro anterior', demoStart: 'Inicio de sesión', demoDownloaded: 'Ejemplo descargado. ', demoNotice: 'Datos ilustrativos guardados en tu navegador. Esta visita no está conectada a un nodo; la descarga no es un paquete SurStor firmado.',
  recordBrief: 'Resumen del cliente', recordBriefType: 'Nota fuente', recordBriefContent: 'El cliente necesita la propuesta de lanzamiento para el viernes 25 de septiembre. El presupuesto aprobado es de 12.000 $.', recordProposal: 'Propuesta de lanzamiento', recordProposalType: 'Borrador de IA', recordProposalContent: 'Lanzamiento en dos fases: un piloto interno seguido de una publicación pública. Entrega la propuesta el 25 de septiembre y mantén la entrega dentro del presupuesto aprobado de 12.000 $.', recordReview: 'Decisión de revisión', recordReviewType: 'Nota de revisión', recordReviewContent: 'La propuesta está lista para revisión humana. La publicación pública aún necesita la aprobación del cliente.',
  searchEyebrow: 'Encuéntralo otra vez / Búsqueda semántica', searchTitleA: 'Recuerda el significado.', searchTitleB: 'Encuentra el trabajo.', searchBody: 'Tus palabras pueden cambiar. Tu trabajo sigue ahí. El nodo local de SurStor busca artefactos por significado y devuelve registros completos.', searchLocal: 'Los embeddings y la búsqueda funcionan en el nodo con un modelo incluido. No se necesita una API externa de embeddings. El índice puede reconstruirse a partir de los registros.', searchChoose: 'ELIGE UNA PREGUNTA DE EJEMPLO', searchMatch: 'Coincidencia ilustrativa', searchWhy1: 'Una pregunta sobre el plazo lleva al límite del resumen original.', searchWhy2: '“Límite de gasto” conecta con el presupuesto aprobado aunque no use esas palabras exactas.', searchWhy3: 'La nota de revisión captura la aprobación que aún falta.', searchNotice: 'Son ejemplos seleccionados, no resultados de búsqueda semántica en vivo. Conecta un nodo local para buscar tus propios artefactos.', queryDue: '¿Cuándo vence la propuesta?', queryBudget: '¿Cuál es el límite de gasto?', queryApproval: '¿Quién debe aprobar el lanzamiento?',
  integrityEyebrow: 'Confía en el registro / Ejercicio de integridad', integrityTitleA: 'Cambia el registro.', integrityTitleB: 'Observa la diferencia.', integrityBody: 'Edita la muestra y compárala con el original. Incluso un pequeño cambio produce un registro diferente.', integrityLabel: 'Registro de muestra editable', integrityCheck: 'Comprobar registro', integrityChanged: 'Probar un presupuesto cambiado', integrityReset: 'Restablecer', integrityReady: 'Listo. Comprueba el original o haz una edición primero.', integrityValid: '✓ Sin cambios — la muestra coincide con el original.', integrityDetected: '✕ Cambio detectado — la muestra ya no coincide.', integrityHow: 'Cómo verifica el nodo real', integrityBinding: 'Vinculación del contenido.', integrityContinuity: 'Continuidad de la sesión.', integritySignature: 'Firma del nodo.', integritySchedule: 'Tabla de costes.', integrityFootnote: 'Este ejercicio del navegador solo compara texto. La verificación real usa hashes, enlaces de sesión y firmas; demuestra integridad, no que el contenido original sea verdadero.',
  quickEyebrow: 'Construye con SurStor / Inicio rápido para desarrolladores', quickTitle: 'Tu primer artefacto verificable.', quickBody: 'Conecta tu flujo de IA al nodo local actual. Guarda un resultado, recupera su procedencia y verifica el registro.', quickSetup: 'Configuración local para desarrolladores.', quickSetupBody: 'Necesitas una copia del código de SurStor. Compila primero las dependencias Covia siguiendo INTEGRATION_NOTES.md; no están disponibles en Maven Central. El nodo confía en llamadas locales y debe permanecer enlazado a 127.0.0.1.', quickNext: 'Siguiente: usa', quickSearch: 'para encontrar artefactos por significado, o', quickExport: 'para crear un paquete de sesión portable y verificarlo sin conexión.', quickStep1: 'Compila e inicia tu nodo', quickStep1Detail: 'Desde el código fuente de SurStor, con Java 21+, Maven y las dependencias Covia instaladas localmente:', quickStep2: 'Conecta un cliente MCP', quickStep2Detail: 'Usa un cliente compatible con HTTP en streaming. Esta es una configuración MCP de ejemplo; la ubicación depende de tu cliente.', quickStep3: 'Guarda tu primer artefacto', quickStep3Detail: 'Llama a surstor_store desde el cliente conectado con estos argumentos. Guarda el id devuelto para el siguiente paso.', quickStep4: 'Recupera y verifica', quickStep4Detail: 'Llama a surstor_retrieve con el id devuelto y después a surstor_verify con el mismo id y deep: true para comprobar la cadena.', copy: 'Copiar', copied: 'Copiado', copyFallback: 'Selecciona el código para copiarlo manualmente.',
  ctaEyebrow: '07 / Prepárate', ctaTitleA: 'Sé auditable.', ctaTitleB: 'Desde hoy.', ctaBody: 'El artículo 12 no es una política que redactas: es infraestructura que ejecutas y ya está vigente. SurStor incorpora equipos de la UE en días, con el registro activo antes de tu próximo despliegue.', ctaPlaceholder: 'correo de trabajo', ctaButton: 'Solicitar acceso', ctaFine: 'solo regiones de la UE · sin tarjeta · DPA desde el primer día',
  footerDescription: 'La capa de registro para la economía europea de la IA. Almacenamiento descentralizado, logs encadenados por hash y soberanía europea por diseño.', footerSystems: 'todos los sistemas operativos — de-fra · nl-ams · ie-dub · se-sto', footerPlatform: 'Plataforma', footerCompliance: 'Cumplimiento', footerCompany: 'Empresa', footerLogPools: 'Grupos de logs', footerRetention: 'Motor de retención', footerExport: 'Exportación para autoridades', footerAgents: 'Grupos de agentes', footerPortable: 'Memoria portable', footerStatus: 'Estado', footerGuide: 'Guía del artículo 12', footerRetentionGuide: 'Retención del Art. 26(6)', footerGdpr: 'Interacción con RGPD', footerPenalties: 'Sanciones del Art. 99', footerTrust: 'Centro de confianza', footerAbout: 'Sobre SurStor', footerResidency: 'Residencia de datos en la UE', footerCareers: 'Empleo', footerContact: 'Contacto', footerLegal: 'SurStor proporciona infraestructura de registro. El contenido de este sitio es informativo y no constituye asesoramiento jurídico.', backJourney: '← Volver a tu ruta', languageLabel: 'Idioma', languageEnglish: 'English', languageSpanish: 'Español', languageFrench: 'Français',
}

const fr: Copy = {
  ...en,
  navWorkflow: 'Votre flux', navOwnership: 'Propriété', navDemo: 'Démo', navDevelopers: 'Développeurs', requestAccess: 'Demander l’accès',
  heroBadge: 'Règlement (UE) 2024/1689 · Article 12', heroTitleA: 'Chaque décision d’IA,', heroTitleB: 'inscrite au registre.', heroBody: 'L’article 12 de la loi européenne sur l’IA oblige les systèmes d’IA à haut risque à enregistrer automatiquement les événements pendant toute leur durée de vie. SurStor est la couche de traçabilité conçue pour cela : des journaux résistants à l’altération, hébergés sur une infrastructure souveraine européenne. Au-delà de la conformité, chaque résultat créé avec n’importe quel outil ou modèle devient votre propriété, portable et affectable où vous le souhaitez.', heroWorkflow: 'Trouver votre flux →', heroObligation: 'Lire l’obligation', heroInForce: 'L’article 12 est en vigueur pour les systèmes de l’annexe III', heroSince: 'depuis le 2 août 2026', heroLive: 'actif', heroHash: 'chaîné par hash · ajout uniquement', heroRetention: 'rétention ≥ 183 jours', heroRegion: 'Région d’exemple',
  journeyEyebrow: 'Trouvez votre parcours / Visite guidée', journeyTitle: 'Que construirez-vous avec SurStor ?', journeyBody: 'Choisissez votre flux, découvrez comment il s’intègre, explorez un exemple et trouvez la prochaine étape.', journeyChoose: 'Choisir votre cas d’usage', journeyExplore: 'Explorer le flux', journeyNext: 'Passer à l’étape suivante', journeyShow: 'Afficher mon flux →', journeyStart: 'Comment commencer ? →', journeyBack: 'Retour', journeyExample: 'Essayer l’exemple d’abord', journeyReturn: 'Retour à votre parcours', journeyIllustrative: 'Les démos utilisent des données illustratives.',
  devName: 'Développeurs', devGoal: 'Conservez le contexte derrière votre code.', devScenario: 'Un assistant IA produit un correctif. Enregistrez son résultat et sa provenance, puis comparez-le à la version suivante.', devStep1: 'Enregistrez les brouillons et le code dans une session.', devStep2: 'Retrouvez l’agent, le modèle et l’heure de chaque artefact.', devStep3: 'Comparez les versions avec surstor_diff.', devAction: 'Explorer une session d’exemple', devNext: 'Connecter votre nœud local',
  agentName: 'Créateurs d’agents IA', agentGoal: 'Suivez le travail entre les agents.', agentScenario: 'Un agent de recherche transmet un brief à un agent de rédaction. Gardez leurs résultats dans une session traçable.', agentStep1: 'Capturez le résultat de chaque agent avec son identifiant.', agentStep2: 'Suivez la séquence des enregistrements liés.', agentStep3: 'Récupérez les artefacts précédents pour l’étape suivante.', agentAction: 'Suivre le transfert d’exemple',
  researcherName: 'Chercheurs', researcherGoal: 'Retrouvez le travail dont vous vous souvenez.', researcherScenario: 'Vous vous souvenez d’une conclusion, mais pas de sa formulation ni de la session. Cherchez par sens et retrouvez l’original.', researcherStep1: 'Enregistrez vos analyses et résultats de modèles.', researcherStep2: 'Interrogez votre nœud avec une question en langage naturel.', researcherStep3: 'Récupérez l’artefact complet avec sa provenance.', researcherAction: 'Explorer les exemples de recherche', researcherNext: 'Configurer la recherche locale',
  complianceName: 'Équipes conformité', complianceGoal: 'Vérifiez l’intégrité d’un enregistrement.', complianceScenario: 'Un réviseur doit inspecter un flux d’IA. Exportez la session et vérifiez les enregistrements indépendamment.', complianceStep1: 'Capturez les artefacts avec leurs métadonnées de provenance.', complianceStep2: 'Vérifiez les liens de contenu, de session et les signatures.', complianceStep3: 'Exportez un paquet de session vérifiable hors ligne.', complianceAction: 'Essayer l’exercice d’intégrité', complianceNext: 'Parler de vos besoins',
  howEyebrow: 'Comment fonctionne SurStor / Quatre étapes', howTitle: 'Du résultat d’IA à un enregistrement vérifiable.', howBody: 'Connectez-vous une fois, capturez le travail important et gardez un moyen de le retrouver et de le vérifier.', howConnect: 'Connecter', howConnectBody: 'Connectez un client compatible MCP à votre nœud SurStor local. Votre flux choisit les résultats à capturer.', howConnectDetail: 'Votre flux → votre nœud', howConnectLink: 'Configurer la connexion', howStore: 'Enregistrer', howStoreBody: 'Enregistrez un résultat avec sa session, son agent et son modèle. SurStor conserve sa provenance et le relie à l’historique.', howStoreDetail: 'Résultat → artefact enregistré', howStoreLink: 'Explorer un enregistrement', howFind: 'Retrouver', howFindBody: 'Recherchez le travail par son sens, puis récupérez l’artefact original et sa provenance. La recherche s’exécute sur votre nœud local.', howFindDetail: 'Question → travail original', howFindLink: 'Essayer les exemples de recherche', howVerify: 'Vérifier et exporter', howVerifyBody: 'Vérifiez les liens de contenu, de session et les signatures. Exportez un paquet vérifiable indépendamment et hors ligne.', howVerifyDetail: 'Session → preuve portable', howVerifyLink: 'Explorer les contrôles d’intégrité', howDisclaimer: 'Ce flux décrit le nœud local actuel. Les exemples utilisent des données de démonstration ; la vérification contrôle l’intégrité, pas la véracité du contenu original.',
  demoEyebrow: 'Explorer SurStor / Visite du produit', demoTitle: 'Chaque résultat a une histoire.', demoBody: 'Suivez un brief dans un flux d’IA. Ouvrez un enregistrement pour voir ce qui a été conservé, qui l’a produit et où il se trouve.', demoSession: 'SESSION D’EXEMPLE', demoSessionName: 'Plan de lancement / 3 enregistrements', demoDownload: 'Télécharger le JSON d’exemple ↓', demoAgent: 'Agent', demoModel: 'Modèle', demoCaptured: 'Capturé · 18 sept. 2026', demoPrevious: 'Enregistrement précédent', demoStart: 'Début de session', demoDownloaded: 'Exemple téléchargé. ', demoNotice: 'Données illustratives conservées dans votre navigateur. Cette visite n’est pas connectée à un nœud ; le téléchargement n’est pas un paquet SurStor signé.',
  recordBrief: 'Brief client', recordBriefType: 'Note source', recordBriefContent: 'Le client a besoin de la proposition de lancement pour le vendredi 25 septembre. Le budget approuvé est de 12 000 $.', recordProposal: 'Proposition de lancement', recordProposalType: 'Brouillon IA', recordProposalContent: 'Lancement en deux phases : un pilote interne puis une publication publique. Remettez la proposition le 25 septembre et restez dans le budget approuvé de 12 000 $.', recordReview: 'Décision de revue', recordReviewType: 'Note de revue', recordReviewContent: 'La proposition est prête pour une revue humaine. La publication publique nécessite encore l’approbation du client.',
  searchEyebrow: 'Le retrouver / Recherche sémantique', searchTitleA: 'Retenez le sens.', searchTitleB: 'Retrouvez le travail.', searchBody: 'Vos mots peuvent changer. Votre travail reste là. Le nœud local SurStor recherche les artefacts par leur sens et renvoie les enregistrements complets.', searchLocal: 'Les embeddings et la recherche s’exécutent sur le nœud avec un modèle intégré. Aucune API d’embedding externe n’est nécessaire. L’index peut être reconstruit à partir des enregistrements.', searchChoose: 'CHOISISSEZ UNE QUESTION D’EXEMPLE', searchMatch: 'Correspondance illustrative', searchWhy1: 'Une question de délai renvoie à l’échéance du brief original.', searchWhy2: '« Limite de dépense » renvoie au budget approuvé, même sans reprendre les mêmes mots.', searchWhy3: 'La note de revue décrit l’approbation encore nécessaire.', searchNotice: 'Ce sont des exemples sélectionnés, pas des résultats de recherche sémantique en direct. Connectez un nœud local pour chercher vos propres artefacts.', queryDue: 'Quand la proposition est-elle due ?', queryBudget: 'Quelle est la limite de dépense ?', queryApproval: 'Qui doit approuver le lancement ?',
  integrityEyebrow: 'Faire confiance au registre / Exercice d’intégrité', integrityTitleA: 'Modifiez le registre.', integrityTitleB: 'Voyez la différence.', integrityBody: 'Modifiez l’exemple, puis comparez-le à l’original. Même un petit changement produit un enregistrement différent.', integrityLabel: 'Enregistrement d’exemple modifiable', integrityCheck: 'Vérifier l’enregistrement', integrityChanged: 'Essayer un budget modifié', integrityReset: 'Réinitialiser', integrityReady: 'Prêt. Vérifiez l’original ou faites d’abord une modification.', integrityValid: '✓ Inchangé — l’exemple correspond à l’original.', integrityDetected: '✕ Modification détectée — l’exemple ne correspond plus.', integrityHow: 'Comment le nœud vérifie le travail', integrityBinding: 'Liaison du contenu.', integrityContinuity: 'Continuité de session.', integritySignature: 'Signature du nœud.', integritySchedule: 'Barème des coûts.', integrityFootnote: 'Cet exercice compare uniquement le texte. La vérification réelle utilise des hashes, des liens de session et des signatures ; elle établit l’intégrité, pas la vérité du contenu original.',
  quickEyebrow: 'Construire avec SurStor / Démarrage développeur', quickTitle: 'Votre premier artefact vérifiable.', quickBody: 'Connectez votre flux d’IA au nœud local actuel. Enregistrez un résultat, récupérez sa provenance et vérifiez le registre.', quickSetup: 'Configuration locale développeur.', quickSetupBody: 'Un checkout du code SurStor est requis. Compilez d’abord les dépendances Covia en suivant INTEGRATION_NOTES.md ; elles ne sont pas disponibles sur Maven Central. Le nœud fait confiance aux appels locaux et doit rester lié à 127.0.0.1.', quickNext: 'Ensuite : utilisez', quickSearch: 'pour trouver les artefacts par leur sens, ou', quickExport: 'pour créer un paquet de session portable vérifiable hors ligne.', quickStep1: 'Construire et démarrer votre nœud', quickStep1Detail: 'Depuis le code source SurStor, avec Java 21+, Maven et les artefacts Covia requis installés localement :', quickStep2: 'Connecter un client MCP', quickStep2Detail: 'Utilisez un client compatible avec HTTP en streaming. Voici une configuration MCP d’exemple ; son emplacement dépend du client.', quickStep3: 'Enregistrer votre premier artefact', quickStep3Detail: 'Appelez surstor_store depuis le client connecté avec ces arguments. Conservez l’identifiant renvoyé pour l’étape suivante.', quickStep4: 'Récupérer et vérifier', quickStep4Detail: 'Appelez surstor_retrieve avec l’identifiant renvoyé, puis surstor_verify avec le même identifiant et deep: true pour vérifier la chaîne.', copy: 'Copier', copied: 'Copié', copyFallback: 'Sélectionnez le code pour le copier manuellement.',
  ctaEyebrow: '07 / Passez à l’action', ctaTitleA: 'Soyez auditable.', ctaTitleB: 'Dès aujourd’hui.', ctaBody: 'L’article 12 n’est pas une politique à rédiger : c’est une infrastructure à exploiter, déjà en vigueur. SurStor intègre les équipes européennes en quelques jours, avec la traçabilité active avant votre prochain déploiement.', ctaPlaceholder: 'e-mail professionnel', ctaButton: 'Demander l’accès', ctaFine: 'régions UE uniquement · sans carte bancaire · DPA dès le premier jour',
  footerDescription: 'La couche de traçabilité pour l’économie européenne de l’IA. Stockage décentralisé, journaux chaînés par hash et souveraineté européenne par conception.', footerSystems: 'tous les systèmes opérationnels — de-fra · nl-ams · ie-dub · se-sto', footerPlatform: 'Plateforme', footerCompliance: 'Conformité', footerCompany: 'Entreprise', footerLogPools: 'Journaux', footerRetention: 'Moteur de rétention', footerExport: 'Export autorités', footerAgents: 'Groupes d’agents', footerPortable: 'Mémoire portable', footerStatus: 'État', footerGuide: 'Guide article 12', footerRetentionGuide: 'Rétention Art. 26(6)', footerGdpr: 'Interaction RGPD', footerPenalties: 'Sanctions Art. 99', footerTrust: 'Centre de confiance', footerAbout: 'À propos', footerResidency: 'Résidence des données UE', footerCareers: 'Carrières', footerContact: 'Contact', footerLegal: 'SurStor fournit une infrastructure de traçabilité. Le contenu de ce site est informatif et ne constitue pas un conseil juridique.', backJourney: '← Retour à votre parcours', languageLabel: 'Langue', languageEnglish: 'English', languageSpanish: 'Español', languageFrench: 'Français',
}

const all = { en, es, fr }

type LanguageContextValue = { language: Language; setLanguage: (language: Language) => void; t: (key: string) => string }
const LanguageContext = createContext<LanguageContextValue | null>(null)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = window.localStorage.getItem('surstor-language') as Language | null
    return stored === 'es' || stored === 'fr' ? stored : 'en'
  })
  const setLanguage = (next: Language) => {
    setLanguageState(next)
    window.localStorage.setItem('surstor-language', next)
  }
  const value = useMemo(() => ({ language, setLanguage, t: (key: string) => all[language][key] ?? en[key] ?? key }), [language])
  useEffect(() => { document.documentElement.lang = language }, [language])
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const value = useContext(LanguageContext)
  if (!value) throw new Error('useLanguage must be used inside LanguageProvider')
  return value
}

export function LanguageSwitcher() {
  const { language, setLanguage, t } = useLanguage()
  return <div className="fixed bottom-4 left-1/2 z-50 flex -translate-x-1/2 items-center gap-1 rounded-full border border-[var(--line-strong)] bg-[var(--surface)]/95 p-1.5 shadow-2xl backdrop-blur" aria-label={t('languageLabel')}>
    {([['en', t('languageEnglish')], ['es', t('languageSpanish')], ['fr', t('languageFrench')]] as const).map(([code, label]) => <button key={code} type="button" aria-pressed={language === code} onClick={() => setLanguage(code)} className={`rounded-full px-3 py-1.5 font-mono2 text-[10px] uppercase tracking-[0.12em] transition-colors ${language === code ? 'bg-[var(--signal)] text-[#0c1626]' : 'text-[var(--text-2)] hover:text-[var(--text-1)]'}`}>{label}</button>)}
  </div>
}
